name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build applications
        run: npm run build

      - name: Lint frontend
        run: npm run lint:frontend

      - name: Type check frontend
        run: npm run typecheck:frontend

      - name: Run backend tests
        run: npm run test:backend

      - name: Run frontend tests
        run: npm run test:frontend
